import React from 'react';
import Head from 'next/head';
import Navbar from '../components/navbar';
import Footer from '../components/footer';

const Layout = ({ children }) => {
  return (
    <>
        <Head>
            <title>Bacaa | Baca Artikel Favoritmu Disini</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
            <main className='md:px-[200px] px-10'>{ children }</main>
        <Footer />
    </>
  );
}

export default Layout